name: Build and Release

on:
  push:
    tags: 
      - 'v*' # 当推送以v开头的标签时触发
  workflow_dispatch: # 允许手动触发

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: install cygwin
      uses: cygwin/cygwin-install-action@master
      with:
        packages: zlib-devel
        
    - name: Run make.sh
      run: |
        sed -i 's/\r$//' ./make.sh
        bash ./make.sh
        
    - name: Create release archive
      shell: bash
      run: |
        # 创建zip压缩包
        version=$(date +'%Y%m%d-%H%M%S')
        zip -r bin-$version.zip bin/
        echo "RELEASE_FILE=bin-$version.zip" >> $GITHUB_ENV
        
    - name: Upload release
      if: startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v1
      with:
        files: ${{ env.RELEASE_FILE }}
